#pragma once

#define IOCP_ERROR_ALLOC_CTX					1
#define IOCP_ERROR_WSA_STARTUP					2
#define IOCP_ERROR_CREATE_IOCP					3
#define IOCP_ERROR_CREATE_LISTEN_SOCKET			4
#define IOCP_ERROR_CONVERT_IP_ADDRESS			5
#define IOCP_ERROR_BIND							6
#define IOCP_ERROR_LISTEN						7
#define IOCP_ERROR_CREATE_ACCEPTOR_SOCKET		8
#define IOCP_ERROR_ALLOC_ACCEPTOR_BUFFER		9
#define IOCP_ERROR_ACCEPT_PENDING				10
#define IOCP_ERROR_CREATE_IOCP_WITH_LISTENER	11
#define IOCP_ERROR_ON_CONNECTED_FPTR_NOT_SET	12
#define IOCP_ERROR_ON_DISCONNECTED_FPTR_NOT_SET	13
#define IOCP_ERROR_ON_RECEIVED_FPTR_NOT_SET		14
#define IOCP_ERROR_ON_SENDED_FPTR_NOT_SET		15
#define IOCP_ERROR_ALLOC_THREADS_CONTAINER		16
#define IOCP_ERROR_CREATE_THREAD				17
#define IOCP_ERROR_RECV							18
#define IOCP_ERROR_SEND							19
